{% set name = "cubo" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cubo-{{ version }}.tar.gz
  sha256: 61cc62c8916c7ac8c332e3913b766730da80d0636473f1c0708c8efd7d56eb1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dask-core >=2021.9.1
    - numpy
    - pandas
    - planetary-computer
    - pyproj
    - pystac-client
    - rasterio
    - stackstac
    - xarray

test:
  imports:
    - cubo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davemlz/cubo
  summary: Easily create EO mini cubes from STAC in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://cubo.readthedocs.io/en/latest/
  dev_url: https://github.com/davemlz/cubo

extra:
  recipe-maintainers:
    - davemlz
