{% set name = "cubo" %}
{% set version = "2023.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cubo-{{ version }}.tar.gz
  sha256: f7c08eab7345747b769a2c7a7882bec286e4f2b2a12690222026802cd5a1a8a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - dask-core >=2023.7.0
    - pandas >=2.0.3
    - planetary-computer >=1.0.0
    - pystac-client >=0.7.2
    - stackstac >=0.4.4
    - xarray >=2023.6.0

test:
  imports:
    - cubo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/davemlz/cubo
  summary: Easily create EO mini cubes from STAC in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://cubo.readthedocs.io/en/latest/
  dev_url: https://github.com/davemlz/cubo

extra:
  recipe-maintainers:
    - davemlz
